# If using AWS Control Tower, ensure that all the specified Organizational Units (OU)
# have been created and enrolled as the accelerator will verify that the OU layout
# matches before continuing to execute the deployment pipeline.

enable: false
organizationalUnits:
  - name: Security
  - name: Infrastructure
quarantineNewAccounts:
  enable: false
  scpPolicyName: Quarantine
serviceControlPolicies: []
# https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_tag-policies.html
taggingPolicies: []
backupPolicies: []
